---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capi-clusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/m-over/capi-infra.git
      revision: HEAD
      directories:
      - path: clusters/*
      - path: clusters/bootstrap
        exclude: true
  template:
    metadata:
      name: 'capi-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/m-over/capi-infra.git
        targetRevision: HEAD
        path: clusters/{{path[1]}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: guestbook
      ignoreDifferences:
      - group: ""
        kind: Secret
        name:  linkerd-proxy-injector-k8s-tls
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
