---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/m-over/capi-infra.git
      targetRevision: HEAD
      directories:
      - path: clusters/*
  template:
    metadata:
      name: 'capi-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/m-over/capi-infra.git
        targetRevision: HEAD
        path: clusters/{{path[1]}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: guestbook
