---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-operator-app
  namespace: argocd
annotations:
  argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/m-over/capi-infra.git'
    path: argo/apps/promOperator/overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - Replace=true
      